#! /bin/bash

pixi run --as-is --locked mlde-data moose extract --collection land-gcm --scenario rcp85 --ensemble-member 01 --year 1981 --variable uwind --frequency day --base-dir /gws/nopw/j04/bris_climdyn/henrya/samb
