domain: birmingham-64
ensemble_members:
- '01'
frequency: day
predictands:
  resolution: 60km-2.2km-coarsened-4x
  collection: land-gcm
  variables:
  - pr
predictors:
  resolution: 60km-2.2km-coarsened-4x
  collection: land-gcm
  variables:
  - psl
  - temp250
  - temp500
  - temp700
  - temp850
  - temp925
  - vorticity250
  - vorticity500
  - vorticity700
  - vorticity850
  - vorticity925
scenario: rcp85
split:
  scheme: random-season
  seed: 42
  test_prop: 0.15
  val_prop: 0.15
