domain: birmingham-64
ensemble_members:
- '01'
- '04'
- '05'
- '06'
- '07'
- '08'
- '09'
- '10'
- '11'
- '12'
- '13'
- '15'
frequency: day
predictands:
  resolution: 2.2km-coarsened-4x-2.2km-coarsened-4x
  collection: land-cpm
  variables:
  - tmean150cm
predictors:
  resolution: 2.2km-coarsened-gcm-2.2km-coarsened-4x
  collection: land-cpm
  variables:
  - psl
  - spechum250
  - spechum500
  - spechum700
  - spechum850
  - temp250
  - temp500
  - temp700
  - temp850
  - vorticity250
  - vorticity500
  - vorticity700
  - vorticity850
scenario: rcp85
split:
  scheme: random-season
  seed: 42
  test_prop: 0.15
  val_prop: 0.15
