scenario: rcp85
ensemble_members:
  - r001i1p00000
  - r001i1p01113
  - r001i1p01554
  - r001i1p01649
  - r001i1p01843
  - r001i1p01935
  - r001i1p02868
  - r001i1p02123
  - r001i1p02242
  - r001i1p02305
  - r001i1p02335
  - r001i1p02491
predictands:
  collection: land-cpm
  domain: engwales
  resolution: 2.2km-coarsened-4x
  frequency: 1hr
  variables:
    - pr
predictors:
  collection: land-cpm
  domain: birmingham-64
  resolution: 2.2km-coarsened-gcm-2.2km-coarsened-4x
  frequency: day
  variables:
      # - pr
      - psl
      - spechum250
      - spechum500
      - spechum700
      - spechum850
      - temp250
      - temp500
      - temp700
      - temp850
      - vorticity250
      - vorticity500
      - vorticity700
      - vorticity850
split:
  scheme: preset
  preset_name: bham64_ccpm-4x_12em_psl-sphum4th-temp4th-vort4th_pr
