#! /usr/bin/env bash

set -euo pipefail

ensemble_member=$1

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

domain="birmingham"
scale_factor="4"
target_resolution="2.2km-coarsened-4x"
target_size=64
frequency="day"
variable="${SCRIPT_DIR}/../../../src/mlde_data/config/variables/${frequency}/land-cpm/tmean150cm.yml"

QUEUE_DEP_PATH=${SCRIPT_DIR}/../../queue-dep-func
BATCH_WRAPPER_PATH=${SCRIPT_DIR}/../../batch-wrapper

echo
echo ${ensemble_member}
echo

# TS1
job_id=0 # no job initially to wait on

years=$(seq 1981 1 2000)
job_id=$(${QUEUE_DEP_PATH} -j ${job_id} -d ${SCRIPT_DIR} -- ${BATCH_WRAPPER_PATH} --variable-config ${variable} --domain ${domain} --scale-factor ${scale_factor} --target-resolution ${target_resolution} --target-size ${target_size} --frequency ${frequency} --ensemble-member ${ensemble_member} ${years})
echo $job_id

# TS2
# job_id=0 # uncomment line to make it not depend on previous job

years=$(seq 2021 1 2040)
job_id=$(${QUEUE_DEP_PATH} -j ${job_id} -d ${SCRIPT_DIR} -- ${BATCH_WRAPPER_PATH} --variable-config ${variable} --domain ${domain} --scale-factor ${scale_factor} --target-resolution ${target_resolution} --target-size ${target_size} --frequency ${frequency} --ensemble-member ${ensemble_member} ${years})
echo $job_id

# TS3
# job_id=0 # uncomment line to make it not depend on previous job

years=$(seq 2061 1 2080)
job_id=$(${QUEUE_DEP_PATH} -j ${job_id} -d ${SCRIPT_DIR} -- ${BATCH_WRAPPER_PATH} --variable-config ${variable} --domain ${domain} --scale-factor ${scale_factor} --target-resolution ${target_resolution} --target-size ${target_size} --frequency ${frequency} --ensemble-member ${ensemble_member} ${years})
echo $job_id
