variable: vorticity700
attrs:
  units: s-1
  standard_name: atmosphere_relative_vorticity
  grid_mapping: rotated_latitude_longitude
  long_name: Relative vorticity at 700 hPa
sources:
  type: canari-le-sprint
  collection: canari-le-sprint
  variables:
    - name: xwind700
      frequency: day
    - name: ywind700
      frequency: day
spec:
  - action: query
    parameters:
      um_atmos_PLEV19: 700
  - action: vorticity
    parameters:
      theta: 700
  - action: regrid_to_target
  - action: select-subdomain
    parameters:
      domain: $domain
  # implicit final actions: assign attrs, save
