variable: pr
attrs:
  units: mm/hour
  standard_name: precipitation_flux
  grid_mapping: rotated_latitude_longitude
sources:
  type: ceda
  collection: land-cpm
  frequency: 1hr
  variables:
    - name: pr
spec:
  - action: coarsen
    parameters:
      scale_factor: ${scale_factor}
      grid_type: pr
  # - action: regrid_to_target
  #   parameters:
  #     target_grid_resolution: ${target_resolution}
  - action: select-subdomain
    parameters:
      domain: $domain
