variable: spechum${theta}
attrs:
  units: 1
  standard_name: specific_humidity
sources:
  type: moose
  collection: land-gcm
  resolution: 60km
  frequency: day
  variables:
    - name: mlqtw
spec:
  - action: query
    parameters:
      query:
        pressure: ${theta}
  - action: shift_lon_break
  - action: select-subdomain
    parameters:
      domain: ${domain}
  # implicit final actions: assign attrs
