variable: tmean150cm
attrs:
  units: K
  standard_name: air_temperature
  grid_mapping: rotated_latitude_longitude
sources:
  type: moose
  collection: land-cpm
  variables:
    # assumes already extracted and converted to nc
    # implicit here is rename variable
    - name: tmean150cm
      frequency: day
spec:
  - action: coarsen
    parameters:
      scale_factor: $scale_factor
      grid: pr
  - action: regrid_to_target
    variable: pr
  - action: select-subdomain
    parameters:
      domain: $domain
